### ISSUE TITLE
Need some help with this weird bug! relating to the LLM refusing to answer opting to make a strange remark instead!

### ISSUE THREAD

**Issue by TheBlewish** [TheBlewish/Web-LLM-Assistant-Llama-cpp#4]
Hi anyone who sees this, I desperately need some help with this problem there is this weird issue where the LLM with often refuse to answer after performing a search instead stating:
"🤖 Assistant:
Based on the absence of selected results and the overall content.
"
I have no idea what causes this, it's consistent across different LLM models, no where in the code does this statement appear at all or even to my recollection similar statements, I have tried various prompt changes and fixes but I can't resolve this issue so far.
I would really really REALLY appreciate if someone could lend me a hand in resolving this weird issue!

**Comment by TheBlewish** [comment]
I have just updated the program, this issue is now fully fixed, the parsing of the final response was causing the issue, this bug is now resolved please let me know if anyone experiences other issues!

**Comment by ali0une** [comment]
Was about to post this. Tested changing user agent, context size, layers offloaded and models ... still had this issue.
Glad you fixed it.

**Comment by TheBlewish** [comment]
> Was about to post this. Tested changing user agent, context size, layers offloaded and models ... still had this issue. Glad you fixed it.

Yeah thanks it took a little bit for me to figure it out, I think it had to do with the parsing, so if you've updated it, is the issue now fixed for you too?

**Comment by ali0une** [comment]
Yes, just tested and it works again!

**Comment by TheBlewish** [comment]
fantastic i'm glad I fixed it for you!
