### ISSUE TITLE
some models are working, other don't

### ISSUE THREAD

**Issue by ali0une** [TheBlewish/Web-LLM-Assistant-Llama-cpp#5]
Hi there.

models i've tested that work :
Phi-3.1-mini-4k-instruct-Q5_K_M.gguf
Meta-Llama-3.1-8B-Instruct-Q5_K_M.gguf
Mistral-Small-Instruct-2409-Q4_K_M.gguf

models that don't :
Mistral-Nemo-Instruct-2407.Q4_K_M.gguf
mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf

related settings :
```
# LLM settings
LLM_CONFIG = {
    "model_path": MODEL_PATH,
    "n_ctx": 16384,  # context size default 20000
    "n_gpu_layers": -1,  # number of layers to offload to GPU (-1 for all, 0 for none)
    "n_threads": 8,  # number of threads to use
    "temp": 0.7,  # temperature for sampling
    "top_p": 0.9,  # top p for sampling
    "top_k": 40,  # top k for sampling
    "repeat_penalty": 1.1,  # repeat penalty
    "max_tokens": 8192,  # max tokens to generate
    "stop": ["User:", "\n\n"]  # stop sequences
}
```

Logs :
```
2024-09-19 18:59:27,591 - ERROR - Error initializing LLM: Failed to load model from file: /whatever/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
Traceback (most recent call last):
  File "/whatever/Web-LLM-Assistant-Llama-cpp/Web-LLM.py", line 105, in initialize_llm
    llm = Llama(**llm_config)
  File "/whatever/Web-LLM-Assistant-Llama-cpp/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 338, in __init__
    self._model = _LlamaModel(
  File "/whatever/Web-LLM-Assistant-Llama-cpp/venv/lib/python3.10/site-packages/llama_cpp/_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /whatever/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
```

**Comment by TheBlewish** [comment]
> Hi there.
> 
> models i've tested that work : Phi-3.1-mini-4k-instruct-Q5_K_M.gguf Meta-Llama-3.1-8B-Instruct-Q5_K_M.gguf Mistral-Small-Instruct-2409-Q4_K_M.gguf
> 
> models that don't : Mistral-Nemo-Instruct-2407.Q4_K_M.gguf mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
> 
> related settings :
> 
> ```
> # LLM settings
> LLM_CONFIG = {
>     "model_path": MODEL_PATH,
>     "n_ctx": 16384,  # context size default 20000
>     "n_gpu_layers": -1,  # number of layers to offload to GPU (-1 for all, 0 for none)
>     "n_threads": 8,  # number of threads to use
>     "temp": 0.7,  # temperature for sampling
>     "top_p": 0.9,  # top p for sampling
>     "top_k": 40,  # top k for sampling
>     "repeat_penalty": 1.1,  # repeat penalty
>     "max_tokens": 8192,  # max tokens to generate
>     "stop": ["User:", "\n\n"]  # stop sequences
> }
> ```
> 
> Logs :
> 
> ```
> 2024-09-19 18:59:27,591 - ERROR - Error initializing LLM: Failed to load model from file: /whatever/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
> Traceback (most recent call last):
>   File "/whatever/Web-LLM-Assistant-Llama-cpp/Web-LLM.py", line 105, in initialize_llm
>     llm = Llama(**llm_config)
>   File "/whatever/Web-LLM-Assistant-Llama-cpp/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 338, in __init__
>     self._model = _LlamaModel(
>   File "/whatever/Web-LLM-Assistant-Llama-cpp/venv/lib/python3.10/site-packages/llama_cpp/_internals.py", line 57, in __init__
>     raise ValueError(f"Failed to load model from file: {path_model}")
> ValueError: Failed to load model from file: /whatever/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
> ```

Hey thanks for letting me know, so can I ask do the models that failed to work run under your Llama.cpp fine without using this program? if so can you please share the CLI input you use to run them successfully with just llama.cpp and tell me if the same settings in the llm_config script don't work even though your llama.cpp does?

If you let me know I can try and figure this issue out the best I can!

**Comment by ali0une** [comment]
```
$ llama-cli -v
main: build = 3758 (3c7989fd)
main: built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu
```

This works :
`/whatever/llama.cpp/llama-server -m /whatever/Mistral-Nemo-Instruct-2407.Q4_K_M.gguf --ctx-size 16384 --threads 8 --temp 0.7 --top-p 0.9 --top-k 40 --repeat-penalty 1.1 --n-gpu-layers -1`

This works once then fills my RAM 100% :
`/whatever/llama.cpp/llama-server -m /whatever/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf --ctx-size 16384 --threads 8 --temp 0.7 --top-p 0.9 --top-k 40 --repeat-penalty 1.1 --n-gpu-layers -1`

So Mistral-Nemo-Instruct-2407.Q4_K_M.gguf should work, for mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf i might be doing something wrong or my system is not capable enough even with lower --ctx-size (NVIDIA 3090 24 Go VRAM)

**Comment by TheBlewish** [comment]
Hey, so I've just done some testing on both Mistral-Nemo-Instruct-2407.Q4_K_M.gguf and mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf

both work fine on my system (NVIDIA 3070) like no issues at all within the program, can you please double check the file paths, and perhaps re-download and reinstall dependencies for the program and see if that fixes it? 

Also you could try setting a specific amount of GPU layers, rather then using all of them if your GPU is struggling, but I am quite confused because your graphics card should be better then mine and mine is working fine! so double check file paths re-download and then let me know how you go because from what I tested there isn't an issue for me!

**Comment by ali0une** [comment]
Many thanks for testing.

it was a PEBKAC as i guess i was using an outdated python wheel for llama-cpp-python (v0.2.76-cu124 instead of v0.2.90-cu124)

Solved with :
`pip install --no-cache-dir https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.90-cu124/llama_cpp_python-0.2.90-cp310-cp310-linux_x86_64.whl`

Both models work now.

**Comment by TheBlewish** [comment]
Cool I'm glad you fixed it! please let me know if there are any other problems that you notice!
